#!/usr/bin/env bash
# Planner: generates bz.yaml from a project brief
# Called by: bz new

generate_config() {
    local brief="$1"
    local cli_cmd="$2"
    local supervisor_model="$3"
    local agent_model="$4"
    local git_strategy="$5"

    # Extract project name from brief or use directory name
    local project_name
    project_name="$(basename "$(pwd)")"

    # For MVP: generate a sensible default config
    # In v2 this will use an LLM call to analyze the brief
    cat > bz.yaml << YAMLEOF
# Generated by bz from project brief
project:
  name: "${project_name}"
  brief: |
$(echo "$brief" | sed 's/^/    /')

supervisor:
  runtime: "${cli_cmd}"
  model: "${supervisor_model}"
  proactive_check_mins: 15
  zombie_heartbeat_mins: 10

agents:
  - id: "researcher"
    runtime: "${cli_cmd}"
    model: "${agent_model}"
    task: |
      Research and document the requirements, APIs, data sources,
      or design decisions needed for this project. Write your findings
      to a markdown doc that other agents can reference.
    focus: ["docs/", "data/"]
    blocked_until: ""

  - id: "developer"
    runtime: "${cli_cmd}"
    model: "${agent_model}"
    task: |
      Implement the project based on the researcher's documentation
      and the project brief. Write clean, working code.
    focus: ["src/"]
    blocked_until: "researcher sets State: done"

git:
  strategy: "${git_strategy}"
  auto_pr: false
YAMLEOF
}
